{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ocean-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ocean-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ocean-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ocean-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
