{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ocean-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ocean-operator.labels" . | indent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - oceanprotocol.com
  resources:
  - workflows
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - secrets
  - persistentvolumeclaim
  verbs:
  - '*'
- apiGroups:
  - batch
  - extensions
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
{{- end }}
