apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocean-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "ocean-operator.labels" . | indent 4 }}
type: Opaque
data:
  account_json: {{ .Values.account_json }}
  account_password: {{ .Values.account_password }}
  aws_access_key_id: {{ .Values.aws_access_key_id }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key }}
