apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.oceanprotocol.com
  labels:
{{ include "ocean-operator.labels" . | indent 4 }}
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
  conversion:
    strategy: None
  group: oceanprotocol.com
  names:
    kind: WorkFlow
    listKind: WorkFlowList
    plural: workflows
    shortNames:
    - wf
    singular: workflow
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        spec:
          description: 'Workflow spececification for a cumputing workflow based on
            Ocean Protocol. More info: https://github.com/oceanprotocol/OEPs/tree/master/12'
          properties:
            '@context':
              description: The description for the @context
              type: string
            authentication:
              description: The description for the authentication
              type: array
            created:
              description: The description for the created
              type: date
            id:
              description: The description for the id
              type: string
            proof:
              description: The description for the proof
              properties:
                created:
                  description: The description for the created
                  type: date
                creator:
                  description: The description for the creator
                  type: string
                signatureValue:
                  description: The description for the signatureValue
                  type: string
                type:
                  description: The description for the type
                  type: string
              type: object
            publicKey:
              description: The description for the publicKey
              items:
                description: The description for the publicKey itemps
                properties:
                  id:
                    description: The description for the id
                    type: string
                  owner:
                    description: The description for the owner
                    type: string
                  type:
                    description: The description for the type
                    type: string
                type: object
              type: array
            service:
              description: The description for the service
              items:
                properties:
                  attributes:
                    description: The properties that define a compute service
                    properties:
                      main:
                        description: The description for the base
                        properties:
                          type:
                            description: The description for the type
                            type: string
                          workflow:
                            description: The description for the workflow
                            properties:
                              stages:
                                items:
                                  description: The description for the items
                                  properties:
                                    index:
                                      description: The description for the index
                                      type: integer
                                    input:
                                      description: The description for the input
                                      items:
                                        description: The description for the items
                                        properties:
                                          id:
                                            description: The description for the id
                                            type: string
                                          index:
                                            description: The description for the index
                                            type: integer
                                        type: object
                                      type: array
                                    output:
                                      description: The description for the output
                                      type: object
                                    requirements:
                                      description: The description for the requirements
                                      properties:
                                        container:
                                          description: The description for the container
                                          properties:
                                            checksum:
                                              description: The description for the
                                                checksum
                                              type: string
                                            image:
                                              description: The description for the
                                                image
                                              type: string
                                            tag:
                                              description: The description for the
                                                tag
                                              type: string
                                          type: object
                                        serverInstances:
                                          description: The description for the serverInstances
                                          type: integer
                                      type: object
                                    stageType:
                                      description: The description for the stageType
                                      type: string
                                    transformation:
                                      description: The description for the transformation
                                      properties:
                                        id:
                                          description: The description for the id
                                          type: string
                                      type: object
                                  type: object
                                type: array
                            required:
                            - stages
                            type: object
                        required:
                        - type
                        - workflow
                        type: object
                    required:
                    - main
                    type: object
                  index:
                    description: The description for the serviceDefinitionId
                    type: integer
                  serviceEndpoint:
                    description: The description for the serviceEndpoint
                    type: string
                  type:
                    description: The description for the type
                    type: string
                type: object
              type: array
  version: v1alpha
  versions:
  - name: v1alpha
    served: true
    storage: true
status:
  acceptedNames:
    kind: WorkFlow
    listKind: WorkFlowList
    plural: workflows
    shortNames:
    - wf
    singular: workflow
  conditions:
  - lastTransitionTime: "2019-07-09T12:03:04Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha
